// @flow
/**
 * Tags Type
 */
export type Tags =
  | 'OFFERED_LIVE'
  | 'STREAMED_WEB'
  | 'STREAMED_MOBILE'
  | 'PREMATCH_STATS'
  | 'VISUALIZATION'
  | 'OPEN_FOR_LIVE'
  | 'SHOW_START_NUMBER'
  | 'MATCH'
  | 'COMPETITION'
  | 'AMERICAN_DISPLAY_FORMAT'
